bound_service_account_names:
- eso-cila-health-microservices-device-ingestion
bound_service_account_namespaces:
- external-secrets
policies:
- staging-cila-health-microservices-device-ingestion
ttl: 24h
