bound_service_account_names:
- eso-cila-health-microservices-identity-access
bound_service_account_namespaces:
- external-secrets
policies:
- staging-cila-health-microservices-identity-access
ttl: 24h
