bound_service_account_names:
- eso-cila-health-microservices-patient-profile
bound_service_account_namespaces:
- external-secrets
policies:
- staging-cila-health-microservices-patient-profile
ttl: 24h
