apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-virtual-vacation-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: staging-virtual-vacation-backend
          serviceAccountRef:
            name: eso-virtual-vacation-backend
            namespace: external-secrets
