apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-autodesk-project-data-api-service
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: staging-autodesk-project-data-api-service
          serviceAccountRef:
            name: eso-autodesk-project-data-api-service
            namespace: external-secrets
