apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-ai-adventure-game-game
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: staging-ai-adventure-game-game
          serviceAccountRef:
            name: eso-ai-adventure-game-game
            namespace: external-secrets
