apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-fintech-infrastructure-keycloak
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: staging-fintech-infrastructure-keycloak
          serviceAccountRef:
            name: eso-fintech-infrastructure-keycloak
            namespace: external-secrets
